[project]
name = "effective-python-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faker>=37.1.0",
    "jupyter>=1.1.1",
    "jupyterlab-git>=0.51.1",
    "pydantic>=2.11.4",
]
